### ISSUE TITLE
Restore sd-bus tests

### ISSUE THREAD

**Issue by emersion** [emersion/basu#9]
Sounds like the test files are here but not compiled. We're missing this:

https://github.com/systemd/systemd/blob/master/src/test/meson.build

**Comment by kennylevinsen** [comment]
A few sd-bus tests now run on master, but:
1. A few tests were not added back due to depending on e.g. glib (test-bus-gvariant, test-bus-introspect).
2. A few tests have been removed due to depending on things that are gone.
3. The tests for e.g. libbasic, busctl and others originally resided in src/test, and I have no attempted to restore those.

Also note that a few tests seem to skip due to lacking a dbus session to talk to on alpine.

**Comment by emersion** [comment]
>Also note that a few tests seem to skip due to lacking a dbus session to talk to on alpine.

Fixed in https://github.com/emersion/basu/commit/44b509df9b3e66bd4ee63a397c566efa3d63d7cb

**Comment by kennylevinsen** [comment]
All libsystemd/sd-bus tests have been restored except test-bus-track due to sd-event usage. We  still don't have libbasic tests though.
